alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
envs:
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "TRUE"
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: s-e-static
    match:
      path:
        prefix: /
name: seahorse-app
region: nyc
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: RyanRonish/S-E
  name: s-e-static
  source_dir: static