alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: s-e
    match:
      path:
        prefix: /
name: sea-turtle-app
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: RyanRonish/S-E
  http_port: 8080
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  name: s-e
  run_command: gunicorn --worker-tmp-dir /dev/shm
  source_dir: /
